Ext.require([
    'Ext.data.Store',
    'Ext.List'
]);

Ext.setup({
    tabletStartupScreen: 'tablet_startup.png',
    phoneStartupScreen: 'phone_startup.png',
    icon: 'icon.png',
    glossOnIcon: false,
    viewport: {
        autoMaximize: false
    },
    onReady : function() {
        Ext.regModel('Contact', {
            fields: ['firstName', 'lastName']
        });

        var store = Ext.create('Ext.data.Store', {
            model: 'Contact',

            sorters: 'firstName',
            getGroupString : function(record) {
                return record.get('firstName')[0];
            },

            data: [
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Ape', lastName: 'Evilias'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Ape', lastName: 'Evilias'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Ape', lastName: 'Evilias'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Ape', lastName: 'Evilias'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Tommy', lastName: 'Maintz'},
                {firstName: 'Ed', lastName: 'Spencer'},
                {firstName: 'Jamie', lastName: 'Avins'},
                {firstName: 'Aaron', lastName: 'Conran'},
                {firstName: 'Dave', lastName: 'Kaneda'},
                {firstName: 'Michael', lastName: 'Mullany'},
                {firstName: 'Abraham', lastName: 'Elias'},
                {firstName: 'Jay', lastName: 'Robinson'},
                {firstName: 'Zed', lastName: 'Zacharias'}
            ]
        });

        Ext.create('Ext.Panel', {
            fullscreen: true,
            layout: 'fit',
            items: {
                xtype: 'list',
                store: store,
                disclosure: true,
                itemConfig: {
                    tpl: '<div class="contact2"><strong>{firstName}</strong> {lastName}</div>'
                }
            }
        });
    }
});
