<?php
/**
 * Created by JetBrains PhpStorm.
 * User: ernesto
 * Date: 6/27/11
 * Time: 3:21 PM
 * To change this template use File | Settings | File Templates.
 */
session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once($_SESSION['site']['root']."/classes/dbHelper.class.php");
//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();

// *************************************************************************************
// Parse the data generated by EXTJS witch is JSON
// *************************************************************************************
$rawData = file_get_contents("php://input");
$data = json_decode($rawData, true);

$row['user_id']             = $data['user_id'];
$row['category']            = $data['category'];
$row['facility']            = $data['facility'];
$row['billing_facillity']   = $data['billing_facillity'];
$row['patient_id']          = $data['patient_id'];
$row['title']               = $data['title'];
$row['status']              = $data['status'];
$row['start']               = $data['start'];
$row['end']                 = $data['end'];
$row['rrule']               = $data['rrule'];
$row['loc']                 = $data['loc'];
$row['notes']               = $data['notes'];
$row['url']                 = $data['url'];
$row['ad']                  = $data['ad'];

// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT statement
// *************************************************************************************
$sql = $mitos_db->sqlBind($row, "calendar_events", "U", "id='" . $data['id'] . "'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();
?>
