<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_update.ejs.php / List Options
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once("../../../library/dbHelper/dbHelper.inc.php");
include_once("../../../library/I18n/I18n.inc.php");
require_once("../../../repository/dataExchange/dataExchange.inc.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_REQUEST['row'] );

//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();

// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************

$row['id'] 				= dataEncode($data->id);
$row['list_id'] 		= dataEncode($data->list_id);
$row['option_id'] 		= dataEncode($data->option_id);
$row['title'] 			= dataEncode($data->title);
$row['seq'] 			= dataEncode($data->seq);
$row['is_default'] 		= (trim($data->is_default) == 'true' ? 1 : 0);
$row['option_value'] 	= dataEncode($data->option_value);
$row['mapping'] 		= dataEncode($data->mapping);
$row['notes'] 			= dataEncode($data->notes);

// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT stament
// *************************************************************************************
$sql = $mitos_db->sqlBind($row, "list_options", "u", "id='".$row['id']."'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

if ( $ret == "" ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}
?>