<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php / List Options
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once($_SESSION['site']['root']."/library/dbHelper/dbHelper.inc.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();

// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_POST['row'], true );

// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************

switch ($_GET['task']) {
	case 'pharmacy':
        //$row['id'] 					    = $data['id'];
		$row['name'] 					= $data['name'];
		$row['transmit_method'] 		= $data['transmit_method'];
		$row['email'] 					= $data['email'];
	break;
	case 'insurance':
        //$row['id'] 					    = $data['id'];
		$row['name'] 					= $data['name'];
		$row['attn'] 					= $data['attn'];
		$row['cms_id'] 					= $data['cms_id'];
		$row['freeb_type'] 				= $data['freeb_type'];
		$row['x12_receiver_id'] 		= $data['x12_receiver_id'];
		$row['x12_default_partner_id'] 	= $data['x12_default_partner_id'];
		$row['alt_cms_id'] 				= $data['alt_cms_id'];
	break;
}
$prow['country_code'] 		        = $data['phone_country_code'];
$prow['area_code'] 		            = $data['phone_area_code'];
$prow['prefix'] 			        = $data['phone_prefix'];
$prow['number'] 			        = $data['phone_number'];

$frow['country_code'] 		        = $data['fax_country_code'];
$frow['area_code'] 			        = $data['fax_area_code'];
$frow['prefix'] 				    = $data['fax_prefix'];
$frow['number'] 				    = $data['fax_number'];

$arow['line1'] 					    = $data['line1'];
$arow['line2'] 					    = $data['line2'];
$arow['city'] 					    = $data['city'];
$arow['state'] 					    = $data['state'];
$arow['zip'] 					    = $data['zip'];
$arow['plus_four'] 				    = $data['plus_four'];
$arow['country'] 				    = $data['country'];


// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT statement
// *************************************************************************************
switch ($_GET['task']) {
	case 'pharmacy':
        $sql = $mitos_db->sqlBind($row, "pharmacies", "U", "id='" . $data['id'] . "'");
        $mitos_db->setSQL($sql);
        $ret = $mitos_db->execLog();
	break;
	case 'insurance':
        $sql = $mitos_db->sqlBind($row, "insurance_companies", "U", "id='" . $data['id'] . "'");
        $mitos_db->setSQL($sql);
        $ret = $mitos_db->execLog();
	break;
}

// *************************************************************************************
// Lets Insert the address for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($arow, "addresses", "U", "id='" .$data['address_id'] . "'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

// *************************************************************************************
// Lets Insert the phone number for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($prow, "phone_numbers", "U", "id='" . $data['phone_id'] . "'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

// *************************************************************************************
// Lets Insert the Fax number for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($frow, "phone_numbers", "U", "id='" . $data['fax_id'] . "'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

if ( $ret != "" ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}
?>