<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

// *************************************************************************************
//SANITIZE ALL ESCAPES
// *************************************************************************************
$sanitize_all_escapes=true;

// *************************************************************************************
//STOP FAKE REGISTER GLOBALS
// *************************************************************************************
$fake_register_globals=false;

// *************************************************************************************
// Load the OpenEMR Libraries
// *************************************************************************************
require_once("../../registry.php");

// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_POST['row'] );

// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************
$row['id'] = trim($data[0]->id);
$row['name'] = htmlspecialchars( trim($data[0]->name), ENT_NOQUOTES );
$row['phone'] = htmlspecialchars( trim($data[0]->phone), ENT_NOQUOTES );
$row['fax'] = htmlspecialchars( trim($data[0]->fax), ENT_NOQUOTES );
$row['street'] = htmlspecialchars( trim($data[0]->street), ENT_NOQUOTES );
$row['city'] = htmlspecialchars( trim($data[0]->city), ENT_NOQUOTES );
$row['state'] = htmlspecialchars( trim($data[0]->state), ENT_NOQUOTES );
$row['postal_code'] = htmlspecialchars( trim($data[0]->postal_code), ENT_NOQUOTES );
$row['country_code'] = htmlspecialchars( trim($data[0]->country_code), ENT_NOQUOTES );
$row['federal_ein'] = htmlspecialchars( trim($data[0]->federal_ein), ENT_NOQUOTES );
$row['x12_sender_id'] = htmlspecialchars( trim($data[0]->x12_sender_id), ENT_NOQUOTES );
$row['service_location'] = (trim($data[0]->service_location) == 'on' ? 1 : 0);
$row['accepts_assignment'] = (trim($data[0]->accepts_assignment) == 'on' ? 1 : 0);
$row['billing_location'] = (trim($data[0]->billing_location) == 'on' ? 1 : 0);
$row['pos_code'] = htmlspecialchars( trim($data[0]->pos_code), ENT_NOQUOTES );
$row['domain_identifier'] = htmlspecialchars( trim($data[0]->domain_identifier), ENT_NOQUOTES );
$row['attn'] = htmlspecialchars( trim($data[0]->attn), ENT_NOQUOTES );
$row['tax_id_type'] = htmlspecialchars( trim($data[0]->tax_id_type), ENT_NOQUOTES );
$row['facility_npi'] = htmlspecialchars( trim($data[0]->facility_npi), ENT_NOQUOTES );

// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT stament
// *************************************************************************************
sqlStatement("UPDATE 
				facility 
			SET
				id = '" . $row['id'] . "', " . "
				name = '" . $row['name'] . "', " . "
				phone = '" . $row['phone'] . "', " . "
				fax = '" . $row['fax'] . "', " . "
				street = '" . $row['street'] . "', " . "
				city = '" . $row['city'] . "', " . "
				state = '" . $row['state'] . "', " . "
				postal_code = '" . $row['postal_code'] . "', " . "
				country_code = '" . $row['country_code'] . "', " . "
				federal_ein = '" . $row['federal_ein'] . "', " . "
				service_location = '" . $row['service_location'] . "', " . " 
				billing_location = '" . $row['billing_location'] . "', " . "
				accepts_assignment = '" . $row['accepts_assignment'] . "', " . "
				pos_code = '" . $row['pos_code'] . "', " . "
				domain_identifier = '" . $row['domain_identifier'] . "', " . "
				attn = '" . $row['attn'] . "', " . " 
				tax_id_type = '" . $row['tax_id_type'] . "', " . "
				facility_npi = '" . $row['facility_npi'] . "' " . " 
			WHERE id ='" . $row['id'] . "'");

?>