<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_update.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once($_SESSION['site']['root']."/classes/dbHelper.class.php");
include_once($_SESSION['site']['root']."/classes/I18n.class.php");
require_once($_SESSION['site']['root']."/classes/dataExchange.class.php");
require_once($_SESSION['site']['root']."/lib/layoutEngine/dataTypes.array.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

$mitos_db = new dbHelper();

// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_REQUEST['row'] );

//---------------------------------------------------------------------------------------
// UOR
// This is just a reverse thing, translate the dataTypes into numbers.
//---------------------------------------------------------------------------------------
$uorTypes = array(
	i18n('Unused', 'r') 	=> 0, 
	i18n('Optional', 'r') 	=> 1, 
	i18n('Required', 'r') 	=> 2
);

//---------------------------------------------------------------------------------------
// Reverse the list_option to get the number and inject it, into the database
//---------------------------------------------------------------------------------------
if ($_SESSION['lang']['code'] == "en_US") { // If the selected language is English, do not translate
	$mitos_db->setSQL("SELECT 
						*
						FROM 
							list_options 
						WHERE 
							list_id = 'lists' AND title='".$data->listDesc."'
						ORDER BY 
							seq");
} else {
	// If a language is selected, translate the list.
	$mitos_db->setSQL("SELECT 
						lo.id,
						lo.list_id,
						lo.option_id, 
						IF(LENGTH(ld.definition),ld.definition,lo.title) AS title ,
						lo.seq,
						lo.is_default,
						lo.option_value,
						lo.mapping,
						lo.notes 
					FROM 
						list_options AS lo 
						LEFT JOIN lang_constants AS lc ON lc.constant_name = lo.title 
						LEFT JOIN lang_definitions AS ld ON ld.cons_id = lc.cons_id AND ld.lang_id = '" . $_SESSION['lang']['code'] . "
					WHERE 
						lo.list_id = 'lists' AND title='".$data->listDesc."'
					ORDER BY 
						IF(LENGTH(ld.definition),ld.definition,lo.title), lo.seq");
}

//---------------------------------------------------------------------------------------
// start the array
//---------------------------------------------------------------------------------------
$reverse_list = array();
foreach($mitos_db->execStatement(PDO::FETCH_ASSOC) as $row){
	array_push($reverse_list, $row);
}

// *************************************************************************************
// Reorder the seq field
// *************************************************************************************
$new_seq = 1;
$row = array();
$mitos_db->setSQL("SELECT 
						*
					FROM
						layout_options
					WHERE
  						form_id = '".$data->form_id."'
  						AND group_name = '".$data->group_name."'
  					ORDER BY
  						seq");
foreach($mitos_db->execStatement(PDO::FETCH_ASSOC) as $urow){
	if($urow['seq'] == $data->seq){ // the seq is equal the user selected update the record
		$row['item_id'] 		= trim($data->item_id);
		$row['form_id'] 		= $data->form_id;
		$row['field_id'] 		= strtolower($data->field_id);
		$row['group_name'] 		= $data->group_name;
		$row['title'] 			= $data->title;
		$row['seq'] 			= $data->seq;
		$row['data_type'] 		= $dataTypes_Reverse[$data->data_type]; // Reverse
		$row['uor'] 			= $uorTypes[$data->uor]; // Reverse
		$row['fld_length'] 		= $data->fld_length;
		$row['max_length'] 		= $data->max_length;
		$row['list_id'] 		= $reverse_list[0]['option_id'];
		$row['titlecols'] 		= $data->titlecols;
		$row['datacols'] 		= $data->datacols;
		$row['default_value'] 	= $data->default_value;
		$row['edit_options'] 	= $data->edit_options;
		$row['description'] 	= $data->description;
		$row['group_order'] 	= $data->group_order;
		// *************************************************************************************
		// Finally that validated POST variables is inserted to the database
		// This one make the JOB of two, if it has an ID key run the UPDATE statement
		// if not run the INSERT stament
		// *************************************************************************************
		$sql = $mitos_db->sqlBind($row, "layout_options", "U", "item_id='" . $row['item_id'] . "'");
		$mitos_db->setSQL($sql);
		$ret = $mitos_db->execLog();
		
		$urow['seq']=$new_seq;
		$sql = $mitos_db->sqlBind($urow, "layout_options", "U", "item_id='" . $urow['item_id'] . "'");
		$mitos_db->setSQL($sql);
		$ret = $mitos_db->execLog();
		$new_seq++;		
	} else {
		$urow['seq']=$new_seq;
		$sql = $mitos_db->sqlBind($urow, "layout_options", "U", "item_id='" . $urow['item_id'] . "'");
		$mitos_db->setSQL($sql);
		$ret = $mitos_db->execLog();
		$new_seq++;
	}
}

if ( $ret[2] <> "" ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}

?>