CREATE TABLE `form_Ambulance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `date` datetime DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `void` tinyint(4) DEFAULT NULL,
  `hr1069` text,
  `mn1069` text,
  `ampm1069` text,
  `mill1069` text,
  `hr1070` text,
  `mn1070` text,
  `ampm1070` text,
  `mill1070` text,
  `hr1071` text,
  `mn1071` text,
  `ampm1071` text,
  `mill1071` text,
  `hr1072` text,
  `mn1072` text,
  `ampm1072` text,
  `mill1072` text,
  `hr1073` text,
  `mn1073` text,
  `ampm1073` text,
  `mill1073` text,
  `hr1074` text,
  `mn1074` text,
  `ampm1074` text,
  `mill1074` text,
  `hampleh` text,
  `hamplea` text,
  `hamplem` text,
  `hamplep` text,
  `hamplel` text,
  `hamplee` text,
  `diagnos` text,
  `signos_y_sintomas` text,
  `otros` text,
  `conciencia` text,
  `piel` text,
  `pulmones` text,
  `abdomen` text,
  `pupilas` text,
  `pupilasid` text,
  `ritmo_cardiaco` text,
  `oxigenolpm` text,
  `oxigenovia` text,
  `suero1` text,
  `angio1` text,
  `lugar1` text,
  `suero2` text,
  `angio2` text,
  `lugar2` text,
  `servicios_prestados` text,
  `escala_de_trauma` text,
  `escala_de_glasqow` text,
  `escala_de_apqar` text,
  `entrega` text,
  `medico` text,
  `mediconpi` text,
  `tratamiento` text,
  `medicoesc` text,
  `medicoescnpi` text,
  `policia` text,
  `policaid` text,
  `querella` text,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8$$

