<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_update.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once("../../../library/dbHelper/dbHelper.inc.php");
include_once("../../../library/I18n/I18n.inc.php");
require_once("../../../repository/dataExchange/dataExchange.inc.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

$mitos_db = new dbHelper();

// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_REQUEST['row'] );

// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************
$row['item_id'] 		= trim($data->item_id);
$row['form_id'] 		= dataEncode($data->form_id);
$row['field_id'] 		= dataEncode($data->field_id);
$row['group_name'] 		= dataEncode($data->group_name);
$row['title'] 			= dataEncode($data->title);
$row['seq'] 			= dataEncode($data->seq);
$row['data_type'] 		= dataEncode($data->data_type);
$row['uor'] 			= dataEncode($data->uor);
$row['fld_length'] 		= dataEncode($data->fld_length);
$row['max_length'] 		= dataEncode($data->max_length);
$row['list_id'] 		= dataEncode($data->list_id);
$row['titlecols'] 		= dataEncode($data->titlecols);
$row['datacols'] 		= dataEncode($data->datacols);
$row['default_value'] 	= dataEncode($data->default_value);
$row['edit_options'] 	= dataEncode($data->edit_options);
$row['description'] 	= dataEncode($data->description);
$row['group_order'] 	= dataEncode($data->group_order);



// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT stament
// *************************************************************************************
$mitos_db->setSQL("UPDATE layout_options 
					  SET item_id 		='".$row['item_id']."',
						  form_id 		='".$row['form_id']."',
						  field_id 		='".$row['field_id']."',
						  group_name 	='".$row['group_name']."',
						  title 		='".$row['title']."',
						  seq 			='".$row['seq']."',
						  data_type 	='".$row['data_type']."',
						  uor 			='".$row['uor']."',
						  fld_length 	='".$row['fld_length']."',
						  max_length 	='".$row['max_length']."',
						  list_id 		='".$row['list_id']."', 
						  titlecols 	='".$row['titlecols']."',
						  datacols		='".$row['datacols']."',
						  default_value ='".$row['default_value']."',
						  edit_options 	='".$row['edit_options']."',
						  description 	='".$row['description']."', 
						  group_order 	='".$row['group_order']."',
					WHERE 
						item_id 		='".$row['item_id'] . "'");
$ret = $mitos_db->execLog();

if ( $ret == "" ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}

?>