<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integration Sencha ExtJS Framework
//
// Integrated by: GI Technologies Inc. in 2011
//
// OpenEMR is a free medical practice management, electronic medical records, prescription writing,
// and medical billing application. These programs are also referred to as electronic health records.
// OpenEMR is licensed under the General Gnu Public License (General GPL). It is a free open source replacement
// for medical applications such as Medical Manager, Health Pro, and Misys. It features support for EDI billing
// to clearing houses such as Availity, MD-Online, MedAvant and ZirMED using ANSI X12.
//
// Sencha ExtJS
// Ext JS is a cross-browser JavaScript library for building rich internet applications. Build rich,
// sustainable web applications faster than ever. It includes:
// * High performance, customizable UI widgets
// * Well designed and extensible Component model
// * An intuitive, easy to use API
// * Commercial and Open Source licenses available
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

include_once($_SESSION['site']['root']."/library/dbHelper/dbHelper.inc.php");
include_once($_SESSION['site']['root']."/library/I18n/I18n.inc.php");
require_once($_SESSION['site']['root']."/repository/dataExchange/dataExchange.inc.php");

//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();

// Parce the data generated by EXTJS witch is JSON
$data = json_decode ( $_POST['row'] );

$row['body']=$data->body;
$row['pid']=$data->pid;
$row['user_id']=$_SESSION['user']['id'];
$row['facility_id']=$_SESSION['site']['facility'];
$row['activity']=$data->activity;
$row['authorized']=$data->authorized;
$row['assigned_to']=$data->assigned_to;
$row['message_status']=$data->message_status;
$row['subject']=$data->subject;
$row['reply_id']=$data->reply_id;
$row['note_type']=$data->note_type;

$sql = $mitos_db->sqlBind($row, "pnotes", "I");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

if ( $ret[2] ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}

?>