CREATE TABLE `dentist_teeth` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` bigint(20) DEFAULT NULL,
  `child_adult` tinyint(4) DEFAULT NULL,
  `teA` text,
  `teB` text,
  `teC` text,
  `teD` text,
  `teE` text,
  `teF` text,
  `teG` text,
  `teH` text,
  `teI` text,
  `teJ` text,
  `teK` text,
  `teL` text,
  `teM` text,
  `teN` text,
  `teO` text,
  `teP` text,
  `teQ` text,
  `teR` text,
  `teS` text,
  `teT` text,
  `te1` text,
  `te2` text,
  `te3` text,
  `te4` text,
  `te5` text,
  `te6` text,
  `te7` text,
  `te8` text,
  `te9` text,
  `te10` text,
  `te11` text,
  `te12` text,
  `te13` text,
  `te14` text,
  `te15` text,
  `te16` text,
  `te17` text,
  `te18` text,
  `te19` text,
  `te20` text,
  `te21` text,
  `te22` text,
  `te23` text,
  `te24` text,
  `te25` text,
  `te26` text,
  `te27` text,
  `te28` text,
  `te29` text,
  `te30` text,
  `te31` text,
  `te32` text,
  `date` datetime DEFAULT NULL,
  `comments` text,
  `groupname` text,
  `user` text,
  `authorized` int(11) DEFAULT NULL,
  `activity` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1

