<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: Ernesto Rodriguez in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();

include_once("library/adoHelper/adoHelper.inc.php");
include_once("library/I18n/I18n.inc.php");
require_once("repository/dataExchange/dataExchange.inc.php");

require_once("library/phpAES/AES.class.php");
$z = "abcdefghijuklmno0123456789012345"; // 256-bit key

$aes = new AES($z);
// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_POST['row'] );

// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************
// general info
$row['username']     = dataEncode($data[0]->username);
$row['password']     = $aes->encrypt($data[0]->password);
$row['title']        = dataEncode($data[0]->title);
$row['fname']        = dataEncode($data[0]->fname);
$row['mname']        = dataEncode($data[0]->mname);
$row['lname']        = dataEncode($data[0]->lname);
$row['authorized']   = (trim($data[0]->authorized) == 'on' ? 1 : 0);
$row['active']   	 = (trim($data[0]->active) == 'on' ? 1 : 0);
$row['facility_id']  = dataEncode($data[0]->facility_id);
$row['see_auth'] 	 = dataEncode($data[0]->see_auth);
$row['taxonomy'] 	 = dataEncode($data[0]->taxonomy);
// access control placeholder...
// $row['none'] 	 = dataEncode($data[0]->none);
$row['federaltaxid'] = dataEncode($data[0]->federaltaxid);
$row['federaldrugid']= dataEncode($data[0]->federaldrugid);
$row['upin']         = dataEncode($data[0]->upin);
$row['npi']          = dataEncode($data[0]->npi);
$row['federaltaxid'] = dataEncode($data[0]->federaltaxid);
$row['specialty']    = dataEncode($data[0]->specialty);
$row['info']         = dataEncode($data[0]->info);



// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT stament
// *************************************************************************************
sqlStatement("INSERT INTO 
        users 
      SET
        username          = '" . $row['username'] . "', " . "
        password          = '" . $row['password'] . "', " . "
        title             = '" . $row['title'] . "', " . "
        fname             = '" . $row['fname'] . "', " . "
        mname             = '" . $row['mname'] . "', " . "
        lname             = '" . $row['lname'] . "', " . "
        authorized        = '" . $row['authorized'] . "', " . "
        active            = '" . $row['active'] . "', " . "
        facility_id       = '" . $row['facility_id'] . "', " . "
        see_auth      	  = '" . $row['see_auth'] . "', " . "
        taxonomy          = '" . $row['taxonomy'] . "', " . "
        federaltaxid      = '" . $row['federaltaxid'] . "', " . "
        federaldrugid     = '" . $row['federaldrugid'] . "', " . "
        upin              = '" . $row['upin'] . "', " . "
        npi               = '" . $row['npi'] . "', " . "
        specialty     	  = '" . $row['specialty'] . "', " . "
        info              = '" . $row['info'] . "'");
?>