<?php 
session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');
require_once('../library/site_setup/class.inc.php');

// *****************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *****************************************************************************************
$post = json_decode ($_POST['row'], true);
// *****************************************************************************************
// create an instance
// *****************************************************************************************
$install = new SiteSetup();

switch ($_GET['task']) {
	// *************************************************************************************
	// Test Connection Only
	// *************************************************************************************
	case "connTest":
		$install->dbHost 	= $_REQUEST['dbHost'];
		$install->dbPort 	= $_REQUEST['dbPort'];
		switch ($_GET['conn']) {
			case "rott":
				$install->rooUser 	= $_REQUEST['rootUser'];
				$install->rootPass 	= $_REQUEST['rootPass'];
			break;
			case "user":
				$install->dbUser 	= $_REQUEST['dbUser'];
				$install->dbPass 	= $_REQUEST['dbPass'];
			break;
		}
  		$install->testConn();
  	break;	// *************************************************************************************
	// Installation with Root Access
	// *************************************************************************************
	case "rootInstall":
		$install->siteName 	= $post['siteName'];
		$install->dbHost 	= $post['dbHost'];
		$install->dbPort 	= $post['dbPort'];
		$install->dbName 	= $post['dbName'];
		$install->rootUser 	= $post['rootUser'];
		$install->rootPass 	= $post['rootPass']; 
		$install->adminUser = $post['adminUser'];
		$install->adminPass = $post['adminPass'];
		
		$install->rootInstall();
	break;
	// *************************************************************************************
	// Installation with Database Access
	// *************************************************************************************
	case "dbInstall":
		$install->siteName 	= $post['siteName'];
		$install->dbUser 	= $post['dbUser'];
		$install->dbPass 	= $post['dbPass'];
		$install->dbHost 	= $post['dbHost'];
		$install->dbPort 	= $post['dbPort'];
		$install->dbName 	= $post['dbName'];
		$install->adminUser = $post['adminUser'];
		$install->adminPass = $post['adminPass'];
		
		$install->dbInstall();
	break;
}


?>

