<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php / List Options
// v0.0.2
// Under GPLv3 License
//
// Integrated by: GI Technologies Inc. in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once($_SESSION['site']['root']."/classes/dbHelper.class.php");
include_once($_SESSION['site']['root']."/classes/I18n.class.php");
require_once($_SESSION['site']['root']."/classes/dataExchange.class.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;
//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();
// *************************************************************************************
// Parse the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_POST['row'], true );
// *************************************************************************************
// Get last "id" add 1 and use $new_id to insert the new data
// *************************************************************************************
$mitos_db->setSQL("SELECT id FROM pharmacies ORDER BY id DESC");
$prec = $mitos_db->fetch();
$mitos_db->setSQL("SELECT id FROM insurance_companies ORDER BY id DESC");
$irec = $mitos_db->fetch();

$new_id = max($prec['id'], $irec['id']) +1;
//echo $new_id;
//exit;
// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************
switch ($_GET['task']) {
	case 'pharmacy':
        $row['id']                      = $new_id;
		$row['name'] 					= $data['name'];
		$row['transmit_method'] 		= $data['transmit_method'];
		$row['email'] 					= $data['email'];

        $sql = $mitos_db->sqlBind($row, "pharmacies", "I");
	break;
	case 'insurance':
        $row['id']                      = $new_id;
		$row['name'] 					= $data['name'];
		$row['attn'] 					= $data['attn'];
		$row['cms_id'] 					= $data['cms_id'];
		$row['freeb_type'] 				= $data['freeb_type'];
		$row['x12_receiver_id'] 		= $data['x12_receiver_id'];
		$row['x12_default_partner_id'] 	= $data['x12_default_partner_id'];
		$row['alt_cms_id'] 				= $data['alt_cms_id'];

        $sql = $mitos_db->sqlBind($row, "insurance_companies", "I");
	break;
}
// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT statement
// *************************************************************************************
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();
// *************************************************************************************
// Lets get the last Inserted ID  and use it to insert the address and phone/fax numbers
// *************************************************************************************
$arow['line1'] 			= $data['line1'];
$arow['line2'] 			= $data['line2'];
$arow['city'] 			= $data['city'];
$arow['state'] 			= $data['state'];
$arow['zip'] 			= $data['zip'];
$arow['plus_four'] 		= $data['plus_four'];
$arow['country'] 		= $data['country'];
$arow['foreign_id'] 	= $new_id;

$prow['country_code'] 	= $data['phone_country_code'];
$prow['area_code'] 		= $data['phone_area_code'];
$prow['prefix'] 		= $data['phone_prefix'];
$prow['number'] 		= $data['phone_number'];
$prow['type'] 		    = 2;
$prow['foreign_id'] 	= $new_id;

$frow['country_code'] 	= $data['fax_country_code'];
$frow['area_code'] 		= $data['fax_area_code'];
$frow['prefix'] 		= $data['fax_prefix'];
$frow['number'] 		= $data['fax_number'];
$frow['type'] 		    = 5;
$frow['foreign_id'] 	= $new_id;
// *************************************************************************************
// Lets Insert the address for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($arow, "addresses", "I");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execOnly();
// *************************************************************************************
// Lets Insert the phone number for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($prow, "phone_numbers", "I");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execOnly();
// *************************************************************************************
// Lets Insert the Fax number for the new pharmacy or insurance
// *************************************************************************************
$sql = $mitos_db->sqlBind($frow, "phone_numbers", "I");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execOnly();
?>