<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: Ernesto Rodriguez in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------
session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');
include_once("../../../library/dbHelper/dbHelper.inc.php");
include_once("../../../library/I18n/I18n.inc.php");
require_once("../../../repository/dataExchange/dataExchange.inc.php");
require_once("../../../library/phpAES/AES.class.php");
//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;
//-------------------------------------------
// password to AES and validate
//-------------------------------------------
$aes = new AES($_SESSION['site']['AESkey']);
//------------------------------------------
// Database class instance
//------------------------------------------
$mitos_db = new dbHelper();
// *************************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *************************************************************************************
$data = json_decode ( $_POST['row'], true );
// *************************************************************************************
// Validate and pass the POST variables to an array
// This is the moment to validate the entered values from the user
// although Sencha EXTJS make good validation, we could check again 
// just in case 
// *************************************************************************************
$row['id'] 				  = trim($data['id']);
$row['username']          = dataEncode($data['username']);
$row['password']       	  = $aes->encrypt($data['password']);
$row['abook_type']        = dataEncode($data['abook_type']);
$row['title']             = dataEncode($data['title']);
$row['fname']             = dataEncode($data['fname']);
$row['mname']             = dataEncode($data['mname']);
$row['lname']             = dataEncode($data['lname']);
$row['specialty']         = dataEncode($data['specialty']);
$row['organization']      = dataEncode($data['organization']);
$row['valedictory']       = dataEncode($data['valedictory']);
$row['street']            = dataEncode($data['street']);
$row['streetb']           = dataEncode($data['streetb']);
$row['city']              = dataEncode($data['city']);
$row['state']             = dataEncode($data['state']);
$row['zip']               = dataEncode($data['zip']);
$row['street2']           = dataEncode($data['street2']);
$row['streetb2']          = dataEncode($data['streetb2']);
$row['city2']             = dataEncode($data['city2']);
$row['state2']            = dataEncode($data['state2']);
$row['zip2']              = dataEncode($data['zip2']);
$row['phone']             = dataEncode($data['phone']);
$row['phonew1']           = dataEncode($data['phonew1']);
$row['phonew2']           = dataEncode($data['phonew2']);
$row['phonecell']         = dataEncode($data['phonecell']);
$row['fax']               = dataEncode($data['fax']);
$row['email']             = dataEncode($data['email']);
$row['assistant']         = dataEncode($data['assistant']);
$row['url']               = dataEncode($data['url']);
$row['upin']              = dataEncode($data['upin']);
$row['npi']               = dataEncode($data['npi']);
$row['federaltaxid']      = dataEncode($data['federaltaxid']);
$row['taxonomy']          = dataEncode($data['taxonomy']);

// *************************************************************************************
// Finally that validated POST variables is inserted to the database
// This one make the JOB of two, if it has an ID key run the UPDATE statement
// if not run the INSERT statement
// *************************************************************************************
$sql = $mitos_db->sqlBind($row, "users", "U", "id='" . $row['id'] . "'");
$mitos_db->setSQL($sql);
$ret = $mitos_db->execLog();

if ( $ret == "" ){
	echo '{ success: false, errors: { reason: "'. $ret[2] .'" }}';
} else {
	echo "{ success: true }";
}

?>