<?php
//--------------------------------------------------------------------------------------------------------------------------
// data_create.ejs.php
// v0.0.2
// Under GPLv3 License
//
// Integrated by: Ernesto Rodriguez in 2011
//
// Remember, this file is called via the Framework Store, this is the AJAX thing.
//--------------------------------------------------------------------------------------------------------------------------

session_name ( "MitosEHR" );
session_start();
session_cache_limiter('private');

include_once($_SESSION['site']['root']."/classes/dbHelper.class.php");
include_once($_SESSION['site']['root']."/classes/I18n.class.php");
require_once($_SESSION['site']['root']."/classes/dataExchange.class.php");

//******************************************************************************
// Reset session count 10 secs = 1 Flop
//******************************************************************************
$_SESSION['site']['flops'] = 0;

//------------------------------------------------------------------------------
// Database class instance
//------------------------------------------------------------------------------
$mitos_db = new dbHelper();

// *****************************************************************************
// Parce the data generated by EXTJS witch is JSON
// *****************************************************************************
$data = json_decode ( $_POST['row']);

foreach($data as $key => $value ){
	//--------------------------------------------------------------------------
	// lets skip data_id, it doesn't exist in the database
	// this id is for ExtJs use only
	//--------------------------------------------------------------------------
	if($key != 'data_id'){
		//---------------------------------------------------------------------
		// check value is an int and trim it, else dateDecode it
		//---------------------------------------------------------------------
		if(is_int($value)){
			$rec = trim($value);
		} else {
			$rec = dataEncode($value);
		}
		//---------------------------------------------------------------------
		// now lets update new values for each key
		//---------------------------------------------------------------------
		$mitos_db->setSQL("UPDATE globals
			SET   gl_value ='". $rec ."'"."
	      	WHERE gl_name  ='". $key ."'");
		$mitos_db->execLog();
	}
}
include_once($_SESSION['site']['root']."/repo/global_settings/global_settings.php");
echo "{ success: true }";	
?>